'use client'
import { useState } from 'react'
import Link from 'next/link'
import { CheckCircle, Send } from 'lucide-react'

const initial = { name:'', email:'', location:'', profileUrl:'', platform:'', profileHistory:'', availability:'', calls:'', equipment:'', motivation:'', compliance:false, accuracy:false, website:'' }

export default function PartnerApplicationForm() {
  const [form, setForm] = useState(initial); const [loading,setLoading]=useState(false); const [submitted,setSubmitted]=useState(false); const [error,setError]=useState('')
  function change(e: React.ChangeEvent<HTMLInputElement|HTMLTextAreaElement|HTMLSelectElement>) { const t=e.target; setForm({...form,[t.name]: t instanceof HTMLInputElement && t.type==='checkbox' ? t.checked : t.value}) }
  async function submit(e:React.FormEvent){e.preventDefault();setLoading(true);setError('');if(form.website){setSubmitted(true);setLoading(false);return}const accessKey=process.env.NEXT_PUBLIC_WEB3FORMS_ACCESS_KEY;if(!accessKey){setError('The application form is not configured yet. Please email admin@codvoro.com directly.');setLoading(false);return}try{const r=await fetch('https://api.web3forms.com/submit',{method:'POST',headers:{'Content-Type':'application/json',Accept:'application/json'},body:JSON.stringify({access_key:accessKey,subject:`New partner application from ${form.name}`,from_name:'Codvoro Partner Application',...form,compliance:form.compliance?'Confirmed':'No',accuracy:form.accuracy?'Confirmed':'No',botcheck:''})});const d=await r.json().catch(()=>({}));if(!r.ok||!d?.success)throw new Error(d?.message||'Something went wrong. Please try again.');setSubmitted(true)}catch(err){setError(err instanceof Error?err.message:'Something went wrong. Please try again.')}finally{setLoading(false)}}
  if(submitted)return <div className="card p-8 lg:p-12 min-h-[34rem] flex flex-col justify-center items-start"><div className="h-14 w-14 rounded-full bg-emerald-50 flex items-center justify-center"><CheckCircle className="h-7 w-7 text-accent-600"/></div><h2 className="mt-6 text-3xl font-extrabold">Application received</h2><p className="mt-3 text-slate-600 max-w-lg">Thank you. We will review your application and contact you if there is a potential fit.</p><button className="btn-outline mt-7" onClick={()=>{setForm(initial);setSubmitted(false)}}>Submit another application</button></div>
  const label='block text-sm font-semibold text-slate-700 mb-1.5';
  return <div className="card p-7 lg:p-12"><h2 className="text-3xl font-extrabold">Your application</h2><p className="mt-2 mb-8 text-slate-600">Required fields are marked with an asterisk.</p><form onSubmit={submit} className="space-y-6"><input name="website" value={form.website} onChange={change} tabIndex={-1} autoComplete="off" className="hidden" aria-hidden="true"/>
    <div className="grid sm:grid-cols-2 gap-5"><div><label className={label} htmlFor="name">Full name *</label><input className="input-field" id="name" name="name" required value={form.name} onChange={change} autoComplete="name" placeholder="Your full name"/></div><div><label className={label} htmlFor="email">Email *</label><input className="input-field" id="email" name="email" type="email" required value={form.email} onChange={change} autoComplete="email" placeholder="you@email.com"/></div></div>
    <div className="grid sm:grid-cols-2 gap-5"><div><label className={label} htmlFor="location">City and country *</label><input className="input-field" id="location" name="location" required value={form.location} onChange={change} placeholder="Boston, United States"/></div><div><label className={label} htmlFor="platform">Primary platform *</label><select className="input-field" id="platform" name="platform" required value={form.platform} onChange={change}><option value="">Select one…</option><option>Upwork</option><option>Freelancer</option><option>LinkedIn / direct sales</option><option>Other</option></select></div></div>
    <div><label className={label} htmlFor="profileUrl">Professional profile URL *</label><input className="input-field" id="profileUrl" name="profileUrl" type="url" required value={form.profileUrl} onChange={change} placeholder="https://…"/></div>
    <div><label className={label} htmlFor="profileHistory">Tell us about the profile and its work history *</label><textarea className="input-field resize-none" rows={4} id="profileHistory" name="profileHistory" required value={form.profileHistory} onChange={change} placeholder="Age of profile, services, completed projects, ratings, and current activity…"/></div>
    <div className="grid sm:grid-cols-2 gap-5"><div><label className={label} htmlFor="availability">Weekly availability *</label><select className="input-field" id="availability" name="availability" required value={form.availability} onChange={change}><option value="">Select one…</option><option>5–10 hours</option><option>10–20 hours</option><option>20+ hours</option></select></div><div><label className={label} htmlFor="calls">Available for client calls? *</label><select className="input-field" id="calls" name="calls" required value={form.calls} onChange={change}><option value="">Select one…</option><option>Yes, during US business hours</option><option>Yes, with advance notice</option><option>Limited availability</option></select></div></div>
    <div><label className={label} htmlFor="equipment">Describe your laptop and internet reliability *</label><textarea className="input-field resize-none" rows={3} id="equipment" name="equipment" required value={form.equipment} onChange={change} placeholder="Device, operating system, internet connection, and typical availability…"/></div>
    <div><label className={label} htmlFor="motivation">Why does this partnership interest you? *</label><textarea className="input-field resize-none" rows={4} id="motivation" name="motivation" required value={form.motivation} onChange={change} placeholder="What are you hoping to build, and what would make the relationship successful?"/></div>
    <fieldset className="space-y-4 border-t border-slate-200 pt-6"><legend className="text-sm font-bold text-slate-900 mb-4">Confirmations</legend><label className="flex items-start gap-3 text-sm text-slate-600"><input className="mt-1 accent-indigo-600" type="checkbox" name="compliance" required checked={form.compliance} onChange={change}/><span>I agree that all activity must follow applicable platform rules, access policies, and identity requirements. *</span></label><label className="flex items-start gap-3 text-sm text-slate-600"><input className="mt-1 accent-indigo-600" type="checkbox" name="accuracy" required checked={form.accuracy} onChange={change}/><span>I confirm that the information in this application is accurate and that I own or am authorized to represent the profile provided. *</span></label></fieldset>
    {error&&<p className="text-sm text-red-700 bg-red-50 border border-red-200 px-4 py-3 rounded-[var(--radius)]">{error}</p>}<button disabled={loading} className="btn-primary w-full justify-center py-3.5">{loading?'Submitting…':<>Submit application <Send className="h-4 w-4"/></>}</button><p className="text-xs text-slate-500">By submitting, you agree to our <Link className="text-brand-600 hover:underline" href="/privacy">Privacy Policy</Link>.</p>
  </form></div>
}
