import type { Metadata } from 'next'
import Link from 'next/link'
import { ArrowRight, BriefcaseBusiness, Check, FileCheck2, Laptop, MessageSquare, Search, ShieldCheck, Wrench } from 'lucide-react'

export const metadata: Metadata = { title: 'Freelance Partnership', description: 'Build a transparent freelance revenue channel with Codvoro handling research, proposals, technical delivery, and project operations.', alternates: { canonical: '/partner' } }

const partnerItems = ['Maintain ownership and oversight of the account', 'Keep a dedicated laptop and reliable internet available', 'Join client calls when required', 'Represent the business professionally', 'Review important decisions and manage withdrawals', 'Retain financial records and handle your tax reporting']
const teamItems = ['Research and select suitable opportunities', 'Write proposals and cover agreed application costs', 'Prepare talking points and technical details for calls', 'Build, test, deploy, and deliver each project', 'Manage technical work and ongoing project support', 'Provide project records, invoices, and applicable documentation']

export default function PartnerPage() {
  return <>
    <section className="section-pad-sm bg-slate-950 text-white bg-hero-grid"><div className="container-wide grid lg:grid-cols-[1.35fr_.65fr] gap-12 items-end"><div><span className="section-tag section-tag-light">Partner With Codvoro</span><h1 className="text-[2.6rem] sm:text-6xl font-extrabold leading-[1.04] tracking-[-0.035em] max-w-4xl">Your professional channel. <span className="gradient-text-light">Our delivery engine.</span></h1><p className="mt-7 text-lg text-slate-300 max-w-2xl leading-relaxed">Turn an existing or underused freelance channel into a structured revenue stream—with clear ownership, defined responsibilities, and visible project records.</p><div className="mt-9 flex flex-wrap gap-4"><Link href="/partner/apply" className="btn-primary">Apply to partner <ArrowRight className="h-4 w-4"/></Link><a href="#model" className="inline-flex items-center px-7 py-3.5 border border-white/25 rounded-[var(--radius)] font-semibold hover:bg-white/10">See how it works</a></div></div><div className="rule-grid-dark grid grid-cols-2"><div className="p-6"><p className="text-4xl font-extrabold">30%</p><p className="mt-2 text-sm text-slate-400">Partner share</p></div><div className="p-6"><p className="text-4xl font-extrabold">70%</p><p className="mt-2 text-sm text-slate-400">Technical & operations</p></div></div></div></section>

    <section id="model" className="section-pad bg-white"><div className="container-wide"><div className="section-head"><div><span className="section-tag">The Model</span><h2 className="section-title">Clear roles. One shared outcome.</h2></div><p className="section-subtitle">You stay in control of your account and client-facing presence. We handle the technical and operational workload behind successful delivery.</p></div><div className="grid lg:grid-cols-2 gap-px bg-slate-200 border border-slate-200"><div className="bg-white p-8 lg:p-12"><BriefcaseBusiness className="h-8 w-8 text-brand-600"/><p className="mt-6 text-xs font-bold uppercase tracking-[.16em] text-brand-600">The partner · 30%</p><h3 className="mt-2 text-3xl font-extrabold">Own the relationship</h3><ul className="mt-7">{partnerItems.map(x=><li key={x} className="flex gap-3 py-3 border-t border-slate-200 text-slate-700"><Check className="h-5 w-5 text-accent-600 shrink-0 mt-0.5"/>{x}</li>)}</ul></div><div className="bg-white p-8 lg:p-12"><Wrench className="h-8 w-8 text-accent-600"/><p className="mt-6 text-xs font-bold uppercase tracking-[.16em] text-accent-600">Codvoro team · 70%</p><h3 className="mt-2 text-3xl font-extrabold">Run the delivery</h3><ul className="mt-7">{teamItems.map(x=><li key={x} className="flex gap-3 py-3 border-t border-slate-200 text-slate-700"><Check className="h-5 w-5 text-brand-600 shrink-0 mt-0.5"/>{x}</li>)}</ul></div></div></div></section>

    <section className="section-pad bg-slate-100"><div className="container-wide"><div className="section-head"><div><span className="section-tag">Operating Principles</span><h2 className="section-title">Built to be visible and verifiable</h2></div><p className="section-subtitle">The partnership is designed around legitimate work, accurate representation, and records both sides can understand.</p></div><div className="rule-grid grid md:grid-cols-2 lg:grid-cols-4 bg-white">{[
      [Search,'Opportunity fit','We focus on suitable projects—not volume for its own sake.'],[MessageSquare,'Call readiness','You receive the context, talking points, and technical preparation you need.'],[FileCheck2,'Documentation','Agreements, calculations, service invoices, and payments form a clear paper trail.'],[ShieldCheck,'Platform compliance','Identity, access, communication, and activity must follow applicable platform rules.']
    ].map(([Icon,title,text])=>{const I=Icon as typeof Search; return <div key={title as string} className="rule-cell"><I className="h-7 w-7 text-brand-600"/><h3 className="mt-6 text-xl font-extrabold">{title as string}</h3><p className="mt-3 text-sm leading-relaxed text-slate-600">{text as string}</p></div>})}</div></div></section>

    <section className="section-pad bg-white"><div className="container-wide grid lg:grid-cols-[.8fr_1.2fr] gap-14 lg:gap-24"><div><span className="section-tag">A Practical Example</span><h2 className="section-title">Simple project math</h2><p className="section-subtitle mt-6">For $10,000 in project revenue, the standard split is $3,000 to the partner and $7,000 to the technical and operations team. The agreement documents how approved fees and expenses are treated.</p></div><div className="border-t border-slate-900"><div className="grid grid-cols-3 py-5 border-b border-slate-200 text-xs font-bold uppercase tracking-[.12em] text-slate-500"><span>Revenue</span><span>Partner</span><span>Team</span></div><div className="grid grid-cols-3 py-7 border-b border-slate-200 text-2xl sm:text-3xl font-extrabold"><span>$10,000</span><span className="text-brand-600">$3,000</span><span className="text-accent-600">$7,000</span></div><p className="mt-5 text-sm text-slate-500">Illustrative example only. Exact calculations and terms are confirmed in writing for each partnership.</p></div></div></section>

    <section className="section-pad-sm bg-brand-700 text-white"><div className="container-wide flex flex-col lg:flex-row lg:items-center justify-between gap-8"><div><p className="text-sm font-bold uppercase tracking-[.16em] text-brand-200">Start the conversation</p><h2 className="mt-3 text-3xl lg:text-4xl font-extrabold">A focused application. A transparent next step.</h2><p className="mt-3 text-brand-100 max-w-2xl">Tell us about your experience, availability, and professional channel. We review every application personally.</p></div><Link href="/partner/apply" className="inline-flex items-center gap-2 bg-white text-brand-700 font-bold px-7 py-3.5 rounded-[var(--radius)] shrink-0">Apply now <ArrowRight className="h-4 w-4"/></Link></div></section>
  </>
}
